[로또 시뮬레이터] 권순찬 미션 제출합니다.
econo-spring-2021/java-lotto pull request #1
Opened 2021-05-20 19:54 UTC by Kwon770

늦어서 죄송합니다.. 다음 미션부턴 적어도 수요일까지는 제출하겠습니다... 😭
예외처리와 테스트코드 처리는 오후 중으로 완료하겠습니다아..

2021-05-21 07:31 UTC, Kwon770 commented
테스트 코드로 작성가능한 메소드는 전부 처리하였지만, 일부 메인 로직에 대한 테스트코드에서는 여전히 어려움을 겪고 있습니다.
1. 호출되는 서비스 로직 메소드는 public, 서비스 로직 메소드가 필요한 데이터를 처리하는 (controller 내부에서만 사용되는) 메소드는 당연히 private 으로 선언해야 한다고 생각하고 있습니다. 하지만 이 때문에 이전에 말씀해주신대로 근본이 되는 메소드를 테스트 못하더라도 그 메소드가 사용하는 세세한 메소드를 테스트하면 된다는 말씀에 반하여져서 이 부분에 대해 여쭙고 싶습니다.
2. Controller 가 domain 클래스를 생성하여 가지고 있는데, 이는 당연스럽게 다른 클래스에서 접근이 불가합니다. 따라서 다음과 같이
```java
public class LottoController {
...
    private UserAccount userAccount;
    private UserLottoTicket userLottoTicket;
    private WinningLotto winningLotto;
...
public void generateUserLottoTicket() {
        long lottoCount = getBuyingTickeyCount();
        OutputView.printBuyingLotteCount(lottoCount);

        List<LottoTicket> tickets = new ArrayList<>();
        for (int i = 0; i < lottoCount; i++) {
            tickets.add(new LottoTicket());
        }
        userLottoTicket = new UserLottoTicket(tickets);
        userLottoTicket.printLottoTickets();
    }
...
```
다음과 같은 코드에서 userLottoTicket 을 변경하거나 생성해도 userLottoTicket 객체에 접근할 방법이 떠오르지 않습니다 지난 로또 미션에서 가르쳐주신 클래스를 주입하여 확률을 컨트롤한다는 것과는 다른 측면인거 같아서 여쭙고 싶습니다.

2021-05-21 07:37 UTC, Kwon770 commented
3. input, output View를 호출할 위치를 제한적으로 두어야할까요? controller 에서 흐름을 제어하고 있으므로, 그 안에서 호출을 전부하는게 관리하기 편한다고 생각하였지만, 일급 컬렉션을 사용하면서 단순히 getter 을 사용하기 어려움을 겪으니 controller 에서 전부 호출하기 어렵다고 생각하였습니다. 그때문에 어디서든 호출하기위해 outputView를 static화하기도 하였습니다. controller 외에서도 호출해야하는 경우는 다음과 같았습니다.
```java
public void printLottoTickets() {
        for (LottoTicket ticket : lottoTickets) {
            OutputView.printLottoTicket(ticket);
        }
```

4. ExceptionView 또한 비슷한 맥락의 궁금증이 있었습니다. 미션을 해결하면서 입출력외에서는 예외처리를 할 필요를 못느껴서 input, output View 에서 모두 처리하였지만, LottoTicket 과 같은 경우 lottoTicket을 생성하면서 유효성을 검사하는 코드도 보았습니다. 단순히 view단에서만 예외를 처리해야한다는 것은 비약일까요?

---
질문이 좀 많네요 😅 공통 피드백에서 처리될만한 질문이면 공통피드백 자료를 통해 확인하겠습니다!

2021-05-23 03:44 UTC, hotheadfactory requested changes
안녕하세요 순찬님:)
코멘트 확인하고 수정 후 코멘트 부탁드립니다.
그리고 질문하신 내용에 대해 답변 드립니다. 
1. 정확히는, private 메소드를 테스트하는 대신 해당 private 메소드를 사용하는 public 메소드를 테스트하면 된다는 말이었습니다.
2. 도메인에서 뷰를 호출하는 해당 부분의 코드는 getter를 쓰지 않기 위해 그렇게 설계된 것으로 보이는데요, DTO에 대해서 검색해 보고 활용해 보시는 것을 추천드립니다.
3. InputView와 OutputView 모두 상태를 가질 필요가 없으므로 Static화 하는 것이 맞습니다. 
getter 사용을 자제하라는 이유 자체가 List<T>등의 내부적으로 포인터 변수로 작동하는 인스턴스 변수를 getter로 꺼내 컨트롤러나 다른 객체 등에서 원소를 추가하거나 제거하는 등 수정했을 경우 원본 객체의 필드에도 적용되어 결과적으로 객체에 원치 않는 변경이 생기고 불변성이 깨지는 문제 때문인데, 뷰에 사용하기 위한 용도라면 이러한 우려가 없으므로 그냥 getter를 써도 무관합니다.
4. View와 Controller 어느 쪽에서든 적절하다고 생각하는 곳에서 예외를 처리하면 됩니다.

2021-05-23 03:44 UTC, hotheadfactory commented on src/test/java/lotto/InputTest.java
> +        Long money = inputView.getMoney(scanner);
Scanner 부분까지 테스트하기보다는 Scanner에서 받은 String을 Array나 List등 컨트롤러에서 쓰기 편한 형태로 처리하는 메소드를 따로 분리하여, 그 부분만 테스트하는 것이 좋습니다.

2021-05-23 03:44 UTC, hotheadfactory commented on src/main/java/lotto/domain/UserLottoTicket.java
> +        if (count == 6) ticket.setResult(LottoResult.FIRST);
이 부분은 LottoResult가 담당하는 게 어떨까요? enum에 필드를 더 만들어서 등수별로 현재 LottoTicket이 가지고 있는 당첨 금액을 가지고 있는다면 더 깔끔한 처리가 가능하지 않을까요?

2021-05-23 03:44 UTC, hotheadfactory commented on src/main/java/lotto/domain/UserLottoTicket.java
> +            OutputView.printLottoTicket(ticket);
도메인에서 뷰를 호출하고 있습니다.
getter를 쓰지 않기 위해 이렇게 하기보다는, 비즈니스 로직에서의 활용이 아닌 단순 출력을 위해서는 그냥 getter를 쓰는 것이 맞습니다. (불변성이 깨질 위험이 없기 때문)
다만 이 경우에는 그래도 뷰가 도메인을 알아야 하는 문제점이 생기는데, 이를 해결하기 위해선 DTO가 무엇인지 검색해 보고 활용해 보세요.

2021-05-26 07:07 UTC, Kwon770 commented
피드백대로 수정은했지만 enum의 활용 방법과 MVC 구조 설계와 규칙, 테스트 코드 작성과 그 과정에서 dto 활용하는 부분에서 아직 어려움을 겪고 있네요. 테스트 코드는 TDD 개발을 해보면 조금 더 개선을 할 수 있을 것 같다만, MVC구조는 더욱 공부를 해봐야할 것 같습니다.

2021-05-27 07:29 UTC, Kwon770 commented
2주차 미션 구현하였습니다... 테스트 코드와 중간에 리펙토링하면서 구현하니까 어지럽네요.. 다음부턴 TDD 로 구현하고 싶네요..

2021-06-26 16:04 UTC, hotheadfactory requested changes

2021-06-26 16:04 UTC, hotheadfactory commented on src/main/java/lotto/view/OutputView.java
> +        System.out.println("[" + numbers.stream().map(String::valueOf).collect(Collectors.joining(",")) + "]");
Stream을 잘 사용하셨군요!
다만 Stream을 사용할 경우엔 가독성을 위해 점(.)을 기준으로 줄바꿈을 하는 경우가 많습니다.
```suggestion
        String lottoTicket = numbers.stream()
                .map(String::valueOf)
                .collect(Collectors.joining(","));
        System.out.println("[" + lottoTicket + "]");
```

Java 8의 Stream의 활용에 대해서 더 궁금하시면 [모던 자바 인 액션](http://www.yes24.com/Product/Goods/77125987)을 읽어보세요.

2021-06-26 16:04 UTC, hotheadfactory commented on src/test/java/lotto/LottoTicketTest.java
> +    void test_getOneIfWinningNumberExists_exits() {
테스트 메소드의 이름을 아무리 잘 지어도 Case에 대한 읽기 쉬운 설명을 위해서는 한글로 된 설명이 도움이 될 때가 많습니다.
`@DisplayName` 어노테이션을 이용해 각 테스트에 대한 한 줄 정도의 설명을 달아 봅시다.

2021-06-26 16:04 UTC, hotheadfactory commented on src/main/java/lotto/view/InputView.java
> +        try {
현재 입력값에 대한 검증은 전적으로 View에 의존하여 입력값이 숫자가 맞는지만 검증하고, 도메인과 컨트롤러에서 뷰에서 가져온 값에 대해 도메인 특성에 기반한 유효성 검증은 전혀 하지 않고 있네요. 예를 들면, Long이라는 자료형은 마이너스 정수를 저장할 수 있지만, 사용자로부터 로또를 사기 위한 금액을 입력받는 지금 이 상황에서는 사용자가 마이너스 금액을 입력할 수 있으면 안 됩니다. 이러한 예외 처리를 어디서 어떻게 처리해야 할지 고민해 보아요.

2021-06-26 16:04 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoResult.java
> +    public static final Long FIFTH_LOTTO_PRICE = 5000L;
등수별 상금 액수를 따로 상수로 관리하기보단 enum의 새로운 필드를 만들어 등수와 같이 관리하면 코드가 많이 간단해질 것 같습니다.

2021-06-26 16:04 UTC, hotheadfactory commented on src/main/java/lotto/domain/UserLottoTickets.java
> +        if (ticket.getResult() == LottoResult.FIFTH) return LottoResult.FIFTH_LOTTO_PRICE;
예를 들면 이런 부분에서. enum의 장점이 바로 이런 번거로운 작업을 단순화시킬 수 있다는 것입니다.
이 글을 참고해 보세요. https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

2021-07-01 13:36 UTC, Kwon770 commented
입력값에 대한 검증에 관한 수정에 대해서 감이 잘 안옵니다.. 도메인에게도 예외 처리의 책임을 맏기려면, 생성자에서 예외를 확인하고 던짐으로서 view의 입력을 다시 트리거해야한다고 생각하였습니다. 하지만 생성자에서 예외를 던지게되면 필드 초기화가 되지않아 오류가 발생하던데, controller가 domain의 정보를 받아서 예외처리하는 것이 맞을까요?

2021-07-05 17:12 UTC, hotheadfactory commented
controller가 domain의 정보를 받아 검증할 필요는 없고, domain이 예외를 던지면 controller가 catch하고 view를 다시 호출하는 방법을 한번 생각해 볼 수 있지 않을까요. try... catch 문이 컨트롤러에 들어가게 되는 거죠.

2021-07-08 15:02 UTC, Kwon770 commented
피드백에 대한 수정은 모두 완료했습니다! 하지만 예외 처리에 대한 질문이 있어서, 질문에 대한 코드를 빠르게 보여드리기 위해 LottoController.java의 45줄에 남겼습니다.

> public int getManualLottoCount() {
        OutputView.askManualLottoCount();
        return InputView.getManualLottoCount();
        // 음수인지를 파악해야하는 간단하 예외파악을 적용해야 하지만, view나 controller에서 확인하기에는
        // domain의 속성이 노출되는 것 같습니다. 그렇다고 굳이 domain에 필요하지 않는 필드를 domain에 저장하여서
        // domain에서 예외를 파악하는 것도 이상한 것 같은데 어떻게 해야 할까요?
    }

❗️ 아 그리고.. 지금 봤는데, 커밋들을 main 브랜치에 올린 것 같습니다. 풀리퀘 진행중이라 제가 건드리지 못하겠습니다.. 죄송합니다.. 😓

2021-07-10 06:58 UTC, hotheadfactory commented
![스크린샷, 2021-07-10 15-56-58](https://user-images.githubusercontent.com/13493184/125154923-8ace0180-e197-11eb-8a56-7480df84dae4.png)
타깃 브랜치만 변경하면 될 것 같아요. 이미 날린 풀 리퀘스트도 이렇게 수정이 가능합니다.

2021-07-15 04:59 UTC, Kwon770 commented
넵 감사합니다! 아직 change requested 인데, 어떤 부분을 더 수정하여야 할까요?

2021-07-17 15:02 UTC, hotheadfactory approved these changes
리뷰를 달아두고 Submit을 안 했었네요.
여튼 수고하셨습니다!

2021-07-17 15:02 UTC, hotheadfactory commented on src/main/java/lotto/controller/LottoController.java
> +    public void getManualLotto() {
LottoController 내에서만 사용되는 이런 메소드들은 private으로 두는 게 좋을 것 같습니다.

2021-07-17 15:02 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoResult.java
> +    LottoResult(int value, Long price) {
enum의 생성자는 private으로 두어야 합니다.
아마 접근제어자를 입력하지 않으면 기본값이 private이긴 할 거에요.
그래도 왜 enum의 생성자가 private이어야 하는지 공부해보면 굳!

2021-07-17 17:49 UTC, Kwon770 commented
일부 함수를 private로 바꿨습니다. enum의 경우에는 private 접근자는 IDE가 redundant하다고 하여서 조사만 하였습니다. 처음 사용할 때 의아하던 enum 특유의 문법이 이해되었습니다. 쓰기 권한이 없어서 머지는 직접못하네요.

2021-07-20 13:09 UTC, merged