[로또 시뮬레이터] 김송아 미션 제출합니다.
econo-spring-2021/java-lotto pull request #2
Opened 2021-05-21 02:32 UTC by asong57

늦어서 죄송합니다ㅠ 다음에는 늦지 않게 제출하겠습니다!

이번 미션에서 어려움을 특히 느꼈던 부분은
- enum을 활용하는 부분이었습니다. 
 enum 안에도 메소드를 작성해서 활용해야 하는 건지 아니면 제가 구현한 방식이 적절한지 모르겠습니다.
- 그리고 예외 처리 부분을 view 안에 새로운 클래스로 작성하는 것이 맞는 건지 궁금합니다!

2021-05-23 06:32 UTC, hotheadfactory requested changes
수고하셨습니다.
아래 피드백 확인하고 수정 후 다시 리뷰요청 해주세요!

2021-05-23 06:32 UTC, hotheadfactory commented on src/test/java/lotto/LottoTest.java
> +        assertThat(600.0).isEqualTo(calculation.getBenefitPercent(lottoMoney));
assertThat(테스트할 메소드 호출).isEqualTo(기대값) 순서로 적는 것이 맞습니다.

2021-05-23 06:32 UTC, hotheadfactory commented on src/main/java/lotto/Application.java
> +        winningNumbers.setBonusBall(InputView.bonusBallView(winningNumbers.getWinningNumbers()));
WinningNumber 클래스에도 -s를 붙이거나, 변수명에서 -s를 빼거나, 통일이 필요해보입니다.
또한 setter를 쓰지 않도록 리팩토링할 수 있을 것 같아요.

2021-05-23 06:32 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoTicket.java
> +    public void setMatchCount(int matchCount) {
setter는 가급적 사용하지 않는 방향으로 리팩토링 해 봅시다.
객체 생성 시점을 조금 뒤로 미룰 수 있다면, 생성자에서 같이 받는 방식 등을 생각해 볼 수 있습니다.

2021-05-23 06:32 UTC, hotheadfactory commented on src/test/java/lotto/LottoTest.java
> +public class LottoTest {
Lotto 뿐 아니라 Domain 패키지 내에 들어있는 모든 클래스에 대해 테스트를 완료해 주세요!

2021-05-23 06:32 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoTicket.java
> +        return null;
null을 리턴하는 일은 가급적 만들지 않는 것이 좋습니다.

참고: https://dundung.tistory.com/187

2021-05-23 06:32 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoTicket.java
> +    public Rank checkMatchCount() {
이 일은 Rank의 책임이 되어야 할 것 같아요.
Tip: 보통 enum에서 조건에 맞는 객체를 리턴하는 메소드의 이름은 `of()`로 합니다.

2021-05-23 06:32 UTC, hotheadfactory commented on src/main/java/lotto/view/InputView.java
> +        } catch (Exception e) {
커스텀 익셉션의 throw나 try...catch는 뷰 대신 컨트롤러에서 하는 것이 좋습니다.
뷰는 언제든지 다른 것으로, 심지어 자바 코드가 아닌 것(웹 프론트엔드 등)으로도 대체할 수 있어야 하는데, 이렇게 하면 각 뷰 별로 예외 처리를 다 따로 해 주거나, 예외 처리를 할 수 없는 상황도 발생하게 됩니다.

2021-05-27 16:16 UTC, asong57 commented
로또 시뮬레이터 2주차 미션 구현했습니다.
피드백 주신 부분 반영해서 오전에 다시 커밋하겠습니다!

2021-05-28 01:02 UTC, asong57 commented on src/main/java/lotto/domain/LottoTicket.java
> +    public void setMatchCount(int matchCount) {
이부분을 어떻게 해야 할지 잘 모르겠습니다ㅠ 힌트 주시면 감사하겠습니다.

2021-05-28 01:03 UTC, asong57 commented
피드백 주신 부분 반영해보았습니다.
LottoTicket의 setMatchCount()를 사용하지 않는 방법이 잘 떠오르지 않아서 이 부분은 반영하지 못 했습니다. 혹시나 힌트 주시면 감사하겠습니다!

2021-07-05 17:09 UTC, hotheadfactory approved these changes
수고하셨습니다!
밑의 리뷰는 다음 미션을 진행할 때 고민해 보시길 바래요~

2021-07-05 17:09 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoTicket.java
> +        this.lottoNumbers = lottoNumbers;
각각의 로또 번호가 유효한지 (1~45 사이인지, 중복되는 번호는 없는지) 검사하려면 어떻게 해야 할까요?

2021-07-11 11:08 UTC, jbj616 reviewed
잘하셨습니다! 
자바에 대한 지식이 부족해서 이정도 밖에 리뷰를 할 수 없다는 점 양해 부탁드립니다(_ _)

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/Application.java
> +        ArrayList<LottoTicket> lottoTickets = new ArrayList<>();
ArrayList를 사용하신 이유가 있나요???
ArrayList와 LinkedList의 차이에 대해서 한번 짚고 넘어가셨으면 좋겠습니다
또한, Java에서 Interface 개념을 한번 생각해보시고 현재 작성하는 코드에 어떠한 변화를 주면 어떤 이점이 있는지 짚고 넘어가셨으면 좋겠습니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/Application.java
> +        OutputView.finalBenefitPercentView(calculation.getBenefitPercent(lottoMoney));
Application이라는 java파일명에 main 메소드에서 여러가지 로직이 구현되어있는 것 같습니다 메소드 분리를 통해 해당로직이 어떠한 역할을 하는지 명시를 하면 좋을 것 같습니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/controller/InvalidManualInputException.java
> +public class InvalidManualInputException extends Exception{
Format 처리가 되지 않는 것 같습니다 git commit이나 push를 하기전에 꼭 format를 하셨으면 좋겠습니다 단순히 보기 좋다라는 이유도 있지만, 팀원들간에 컨벤션이 될 수 있으며, git conflict도 방지하는 많은 장점이 존재하기 때문입니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/controller/Lotto.java
> +    public static ArrayList<Integer> setOriginalLottoNumbers() {
줄간격도 신경 쓰셨으면 좋겠습니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/controller/Lotto.java
> +    public static ArrayList<Integer> setLottoNumbers(ArrayList<Integer> originalLottoNumbers) {
파라미터나 Return 객체에서 ArrayList를 사용하셨는 데 List를 반환하는 것이랑 어떠한 장단점이 있는지 짚고 넘어가셨으면 좋겠습니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/domain/Calculation.java
> +    public HashMap<Rank, Integer> getResults() {
hashmap(https://d2.naver.com/helloworld/831311)에 대해서 한번 조사해보셨으면 좋겠으며 이또한 Map을 반환하는 것과 무슨 차이가 있는지 짚고 넘어가셨으면 좋겠습니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/domain/Calculation.java
> +        results.put(Rank.FIFTH, 0);
Init을 생성자를 통해 구현하는 것은 어떻게 생각하시나요???

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/domain/LottoTicket.java
> +    public void setBonusball(boolean bonusBall) {
boolean을 사용할 때 해당 변수에 대한 네이밍은 is, can 같은(조동사) 조건에 대한 직관적인 작명을 사용하는 것이 좋아보입니다

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/controller/Lotto.java
> +    public static void calculateMatchResults(ArrayList<LottoTicket> lottoTickets, Calculation calculation){
static 메소드를 사용하신 이유가 있을 까요??

2021-07-11 11:08 UTC, jbj616 commented on src/main/java/lotto/controller/Lotto.java
> +        lottoTicket.setMatchCount(count);
해당 로직을 
`LottoTicket.CheckWinningNumber(WinnNumber)`
위 LottoTicket에 구현하고
해당 메소드를 호출하는 것과는 무슨 차이가 있을가요?

```
public static void checkOneLottoTicketMatchCount(LottoTicket lottoTicket, WinningNumber winningNumber){
    lottoTicket.CheckWinningNumber(winning.......)
}
```

2021-07-14 02:45 UTC, asong57 commented on src/main/java/lotto/Application.java
> +        ArrayList<LottoTicket> lottoTickets = new ArrayList<>();
제대로 생각해 보지 못한 부분이었네요..!
잘 알아보도록 하겠습니다!
Interface는 멀게만 느껴지는 개념이긴 했는데 다시 조사해보고 이점을 알아보도록 하겠습니당!
많은 조언들 감사드려요!!!

2021-07-14 02:46 UTC, asong57 commented on src/main/java/lotto/Application.java
> +        OutputView.finalBenefitPercentView(calculation.getBenefitPercent(lottoMoney));
넵! 이번 블랙잭 미션에 녹여보도록 하겠습니다!

2021-07-14 02:47 UTC, asong57 commented on src/main/java/lotto/controller/InvalidManualInputException.java
> +public class InvalidManualInputException extends Exception{
commit 전 format! 잊지 말아야겠어요!

2021-07-14 02:48 UTC, asong57 commented on src/main/java/lotto/controller/Lotto.java
> +    public static ArrayList<Integer> setLottoNumbers(ArrayList<Integer> originalLottoNumbers) {
이부분도 생각해 본 적이 없었는데 찾아보도록 하겠습니다! 👍

2021-07-14 02:48 UTC, asong57 commented on src/main/java/lotto/domain/Calculation.java
> +    public HashMap<Rank, Integer> getResults() {
조언 감사합니다!! (링크는 들어가지지가 않네요ㅠ)

2021-07-14 02:50 UTC, asong57 commented on src/main/java/lotto/domain/Calculation.java
> +        results.put(Rank.FIFTH, 0);
그렇네요 생성자 활용하는 것이 훨씬 나을 것 같아요!

2021-07-14 02:50 UTC, asong57 commented on src/main/java/lotto/domain/LottoTicket.java
> +    public void setBonusball(boolean bonusBall) {
왜 저렇게 했지,, 잊지 않도록 하겠습니다!

2021-07-14 02:52 UTC, asong57 commented on src/main/java/lotto/controller/Lotto.java
> +    public static void calculateMatchResults(ArrayList<LottoTicket> lottoTickets, Calculation calculation){
Application의 main 메소드에서 실행시키기 위해서 static으로 했었던 것 같은데
Lotto 안에서 실행 로직들을 묶어 놓으면 이 메소드에서는 static이 없어도 될 것 같습니다.. (확신이 서진 않네요..)

2021-07-14 02:56 UTC, asong57 commented on src/main/java/lotto/controller/Lotto.java
> +        lottoTicket.setMatchCount(count);
위 로직은 LottoTicket과 관련이 많이 되어 있는 코드라서 LottoTicket에 구현한다면 
저렇게 새로 lottoNumbers를 만들지 않아도 되고, setBonusBall, setMatchCount를 하지 않고 바로 변수에 접근해서 적용할 수 있을 것 같네요!

2021-07-20 13:10 UTC, merged