[로또 시뮬레이터 1주차] 홍동건 미션 제출합니다.
econo-spring-2021/java-lotto pull request #3
Opened 2021-08-19 11:44 UTC by Hongdonggeon

2021-08-22 18:00 UTC, hotheadfactory requested changes
안녕하세요 동건님~ 오랜만이에요!

리뷰 내용에 따라 수정하고 다시 리뷰요청 해 주세요!

2021-08-22 18:00 UTC, hotheadfactory commented on src/main/java/lotto/controller/GameController.java
> +        return money;
lottoResultShow()는 로또 결과를 출력하는 데 이용해야 할 메소드인데, money를 리턴한다는 건 이상해요.
한 메소드가 한 가지 일만 하도록 리팩토링해 보아요!

2021-08-22 18:00 UTC, hotheadfactory commented on src/main/java/lotto/controller/GameController.java
> +        return benefit;
이것도 마찬가지로 수익 계산과 출력을 동시에 하려다 보니 이렇게 되었는데, 분리해 봅시다!

2021-08-22 18:00 UTC, hotheadfactory commented on src/main/java/lotto/controller/GameController.java
> +                if (winnerTicket.getLottoTicket().getLottoNumbers().get(i) == lottoTicket.getLottoNumbers().get(j))
당첨번호와 산 로또 번호를 비교하는 로직이 컨트롤러에 나와 있는데요,
보다 캡슐화시키기 위해서 둘 중 한 쪽의 클래스에 책임을 지우는 게 어떨까요?

또 한 가지 변수 / 객체를 불러오기 위해서 점(.)을 두 개 이상 사용하는 것은 가급적 피하는 것이 좋습니다. (디미터의 법칙이라고 검색해 보세요)

2021-08-22 18:00 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoTicket.java
> +    public LottoTicket() {
랜덤 로또 번호 생성을 이곳에서 하고 있는데요,
로또 번호 생성만 하는 클래스를 분리해서 LottoTicket은 보다 이미 발급된 로또에 대한 행위에 집중하게 하는 건 어떨까요?
이렇게 하면 아래 25번째 줄처럼 테스트만을 위한 생성자를 만들어야 하는 것도 있고요.

2021-08-22 18:00 UTC, hotheadfactory commented on src/test/java/lotto/LottoTicketTest.java
> +    @DisplayName("티켓이 생성될 때 로또 번호 범위가 1~45인지")
오류를 어떻게 처리하는지에 대해서도 테스트해 주면 좋을 것 같아요.

2021-09-09 02:27 UTC, Hongdonggeon commented
피드백 주신 부분 반영했습니다! 
피드백 항상 감사드립니다 회형님!!
도메인에 기능을 부여하고 역할을 부여하는 것에 어려움이 있었는데 피드백 수정하면서 조금 감을 잡은 것 같아요
로또 2주차 미션도 열심히 달려보겠습니다:)

2021-09-12 14:49 UTC, hotheadfactory approved these changes
수고하셨습니다! 2주차를 진행해 주세요!

2021-09-12 14:49 UTC, hotheadfactory commented on src/main/java/lotto/controller/GameController.java
> +    public LinkedHashMap<LottoResult, Integer> lottoResultShow() {
리턴값의 자료형은 일반적으로는 구체적인 구현체에 의존시키지 않는 습관을 들이는 것이 좋습니다.
예를 들면 LinkedHashMap 대신 Map을 사용하는 식으로요.
다만 여기서는 `Map의 순서가 보장되어야 한다`는 의도가 분명하므로 이렇게 쓰셔도 무방할 것 같습니다!

2021-09-12 14:49 UTC, hotheadfactory commented on src/main/java/lotto/view/InputView.java
> +        String[] winningBallArray = separateWinningBall(winningBallString);
배열과 for문 대신 List와 Stream을 사용해 볼까요?

2021-09-12 14:49 UTC, hotheadfactory commented on src/main/java/lotto/controller/InvalidInputWonBallsException.java
> +    private static String INVALID_INPUT_WON_BALLS_MESSAGE = "지난 주 당첨 번호는 6개를 입력하셔야 됩니다.";
6이라는 숫자도 따로 상수화 하는 것이 좋습니다. 이것이 실제 상용 프로그램이었다면? 이라고 생각하면 혹시나 운영 중에 요구 사항이 바뀔 수도 있으니까요!

2021-09-12 14:49 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoTicket.java
> +            if(lottoNumber<1 || lottoNumber >45) throw new IllegalArgumentException("로또 번호는 1부터 45까지 존재합니다");
인텔리제이의 자동 포맷팅 기능을 이용해 봅시다.
윈도우/리눅스 : Ctrl+Alt+L (포맷팅 정리) Ctrl+Alt+O (사용하지 않는 Import 정리)
맥OS: Opt+Cmd+L (포맷팅 정리) Ctrl+Opt+O (사용하지 않는 Import 정리)

2021-09-12 14:49 UTC, merged

2021-09-15 00:19 UTC, Hongdonggeon commented on src/main/java/lotto/domain/LottoTicket.java
> +            if(lottoNumber<1 || lottoNumber >45) throw new IllegalArgumentException("로또 번호는 1부터 45까지 존재합니다");
유용한 단축키 감사합니다!! 포맷팅 정리도 잊지 않겠습니다!!

2021-09-15 00:21 UTC, Hongdonggeon commented on src/main/java/lotto/controller/InvalidInputWonBallsException.java
> +    private static String INVALID_INPUT_WON_BALLS_MESSAGE = "지난 주 당첨 번호는 6개를 입력하셔야 됩니다.";
아~ 그렇네요! 더 세세하게 봐야겠슴돠

2021-09-15 00:23 UTC, Hongdonggeon commented on src/main/java/lotto/view/InputView.java
> +        String[] winningBallArray = separateWinningBall(winningBallString);
넵!! 알겠습니다!!