[로또 시뮬레이터] 김성혁 미션 제출합니다.
econo-spring-2021/java-lotto pull request #4
Opened 2021-09-08 02:23 UTC by sunghyuki

늦어져서 죄송합니다.

2021-09-08 13:57 UTC, hotheadfactory commented
커밋 단위가 너무 큰 것 같아요. 앞으로는 커밋 단위에도 신경써 주세요~

2021-09-10 01:41 UTC, sunghyuki commented
연습이 조금 부족했던 것 같습니다. 기능 단위 커밋 신경 써서 올리도록 하겠습니다 !

2021-09-12 15:06 UTC, hotheadfactory requested changes
수고하셨습니다! 몇 가지만 수정하면 될 것 같네요.

2021-09-12 15:06 UTC, hotheadfactory commented on README.md
> +- [ ] 로또 구입 금액 입력 받기
완료한 기능에 대해서 체크하고 넘어가는 거 잊지 마세요~

2021-09-12 15:06 UTC, hotheadfactory commented on src/main/java/lotto/controller/Simulator.java
> +        lottoCount = payment.getMoney() / Constants.LOTTO_PRICE;
LOTTO_PRICE는 도메인에 관련된 상수이지, 뷰에 관련되었다 보기 힘들 것 같아요.
lotto.view.Constants가 가지고 있는 게 맞을까요?

2021-09-12 15:06 UTC, hotheadfactory commented on src/main/java/lotto/domain/Lotto.java
> +        List<LottoNumber> lottoNumberRange = new ArrayList<LottoNumber>();
지금은 생성자에서 랜덤 또는 정해진 로또 객체를 만들고 있는데요, `팩토리 메서드 패턴`에 대해 공부해 보고 적용해 봅시다!

2021-09-12 15:06 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoNumber.java
> +    public LottoNumber(int number) {
LottoNumber로 쪼개서 값 검증한 거 굳!!

2021-09-12 15:06 UTC, hotheadfactory commented on src/main/java/lotto/domain/LottoResult.java
> +    public Map<LottoRank, Integer> show(List<LottoRank> lottoRanks) {
뷰에 모델을 의존시키지 않기 위해 이렇게 한 것인가요?
그렇다기엔 LottoRank가 Map 안에 들어가 있는데요...

2021-09-12 15:06 UTC, hotheadfactory commented on src/main/java/lotto/view/OutputView.java
> +import lotto.domain.LottoRank;
뷰에서 도메인을 import하는 일이 없도록 해야 합니다.

2021-09-14 05:04 UTC, sunghyuki commented on README.md
> +- [ ] 로또 구입 금액 입력 받기
넵 체크 표시 하는 것을 깜빡했네요..!

2021-09-14 05:12 UTC, sunghyuki commented on src/main/java/lotto/controller/Simulator.java
> +        lottoCount = payment.getMoney() / Constants.LOTTO_PRICE;
모든 상수를 일괄적으로 Constants 클래스에 묶어서 관리하면 편하겠다는 생각만 했었는데 도메인에 관련된 상수는 도메인에서 관리하는 것이 더 좋겠다는 생각이 드네요 !! 감사합니다 ~~

2021-09-14 05:32 UTC, sunghyuki commented on src/main/java/lotto/domain/Lotto.java
> +        List<LottoNumber> lottoNumberRange = new ArrayList<LottoNumber>();
공부해보고 적용해보겠습니다 !

2021-09-14 05:33 UTC, sunghyuki commented on src/main/java/lotto/domain/LottoNumber.java
> +    public LottoNumber(int number) {
감사합니다 ㅎㅎ

2021-09-14 14:01 UTC, sunghyuki commented on src/main/java/lotto/domain/Lotto.java
> +        List<LottoNumber> lottoNumberRange = new ArrayList<LottoNumber>();
팩토리 메서드 패턴을 공부 중 궁금한 점이 생겼습니다. 팩토리 메서드 패턴을 적용 시 팩토리에서 로또(Lotto)와 당첨로또(WinningLotto)를 생성하는 방법도 존재하겠지만 실제 로또의 관점에서 생각해 볼 때 수동 로또 생성까지의 확장성을 생각한다면 팩토리에서 수동 로또와 자동 로또를 생성하는 편이 더 좋을 것 같다는 생각이 드네요 ! 더 적절한 방법이 있는지 조언 부탁드려도 될까요 ?

2021-10-05 02:40 UTC, sunghyuki commented on src/main/java/lotto/view/OutputView.java
> +import lotto.domain.LottoRank;
https://github.com/econo-spring-2021/java-lotto/pull/4#discussion_r706850939

2021-10-05 02:42 UTC, sunghyuki commented on src/main/java/lotto/view/OutputView.java
> +import lotto.domain.LottoRank;
해당 고민을 컨트롤러에서 LottoResult의 계산을 한 프로세스 작업 단위로 생각해서 메서드로 분리해 보았는데요! 뷰와 도메인이 분리는 되었으나 좋은 방법인지는 모르겠네요 ㅜ

2021-10-07 11:47 UTC, hotheadfactory requested changes

2021-10-07 11:47 UTC, hotheadfactory commented on src/main/java/lotto/controller/Simulator.java
> +    public void start() {
지금 보시면 Simulator가 너무 많은 메소드를 가지고 있어요.
또 지금 이 start라는 메소드도 너무 많은 일을 한 번에 하고 있죠.
일을 조금 분산해보는 게 어떨까요?
대표적으로는 로또 티켓을 만드는 부분을 별도의 클래스로 뺄 수 있을 것 같습니다.

2021-10-12 02:10 UTC, hotheadfactory approved these changes
수고하셨습니다!!

2021-10-12 07:50 UTC, merged